#!/usr/bin/env bash 

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/human/H3K27ac/H3K27ac_human_allInc_blacklisted.bed hg19 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/human/H3K27ac/allInc_none -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/human/H3K27ac/H3K27ac_human_noChange_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/human/H3K27ac/H3K27ac_human_allDec_blacklisted.bed hg19 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/human/H3K27ac/allDec_none -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/human/H3K27ac/H3K27ac_human_noChange_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/human/H3K27ac/H3K27ac_human_allInc_blacklisted.bed hg19 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/human/H3K27ac/allInc_allDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/human/H3K27ac/H3K27ac_human_allDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/human/H3K27ac/H3K27ac_human_allDec_blacklisted.bed hg19 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/human/H3K27ac/allDec_allInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/human/H3K27ac/H3K27ac_human_allInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/human/H3K4me3/H3K4me3_human_allInc_blacklisted.bed hg19 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/human/H3K4me3/allInc_none -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/human/H3K4me3/H3K4me3_human_noChange_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/human/H3K4me3/H3K4me3_human_allDec_blacklisted.bed hg19 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/human/H3K4me3/allDec_none -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/human/H3K4me3/H3K4me3_human_noChange_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/human/H3K4me3/H3K4me3_human_allInc_blacklisted.bed hg19 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/human/H3K4me3/allInc_allDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/human/H3K4me3/H3K4me3_human_allDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/human/H3K4me3/H3K4me3_human_allDec_blacklisted.bed hg19 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/human/H3K4me3/allDec_allInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/human/H3K4me3/H3K4me3_human_allInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/human/H3K4me1/H3K4me1_human_allInc_blacklisted.bed hg19 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/human/H3K4me1/allInc_none -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/human/H3K4me1/H3K4me1_human_noChange_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/human/H3K4me1/H3K4me1_human_allDec_blacklisted.bed hg19 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/human/H3K4me1/allDec_none -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/human/H3K4me1/H3K4me1_human_noChange_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/human/H3K4me1/H3K4me1_human_allInc_blacklisted.bed hg19 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/human/H3K4me1/allInc_allDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/human/H3K4me1/H3K4me1_human_allDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/human/H3K4me1/H3K4me1_human_allDec_blacklisted.bed hg19 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/human/H3K4me1/allDec_allInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/human/H3K4me1/H3K4me1_human_allInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/human/HDAC2/HDAC2_human_allInc_blacklisted.bed hg19 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/human/HDAC2/allInc_none -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/human/HDAC2/HDAC2_human_noChange_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/human/HDAC2/HDAC2_human_allDec_blacklisted.bed hg19 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/human/HDAC2/allDec_none -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/human/HDAC2/HDAC2_human_noChange_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/human/HDAC2/HDAC2_human_allInc_blacklisted.bed hg19 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/human/HDAC2/allInc_allDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/human/HDAC2/HDAC2_human_allDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/human/HDAC2/HDAC2_human_allDec_blacklisted.bed hg19 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/human/HDAC2/allDec_allInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/human/HDAC2/HDAC2_human_allInc_blacklisted.bed  -preparsedDir ~/temp -preparse