#!/usr/bin/env bash

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_dec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K27ac/dec_allInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_allInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_dec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K27ac/dec_earlyInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_earlyInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_dec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K27ac/dec_lateInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_lateInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_dec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K27ac/dec_inc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_inc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_dec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K27ac/dec_none -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_noChange_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_earlyDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K27ac/earlyDec_allInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_allInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_earlyDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K27ac/earlyDec_earlyInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_earlyInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_earlyDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K27ac/earlyDec_lateInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_lateInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_earlyDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K27ac/earlyDec_inc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_inc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_earlyDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K27ac/earlyDec_none -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_noChange_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_lateDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K27ac/lateDec_allInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_allInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_lateDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K27ac/lateDec_earlyInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_earlyInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_lateDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K27ac/lateDec_lateInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_lateInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_lateDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K27ac/lateDec_inc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_inc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_lateDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K27ac/lateDec_none -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_noChange_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_inc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K27ac/inc_allDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_allDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_inc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K27ac/inc_earlyDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_earlyDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_inc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K27ac/inc_lateDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_lateDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_inc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K27ac/inc_dec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_dec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_inc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K27ac/inc_none -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_noChange_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_earlyInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K27ac/earlyInc_allDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_allDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_earlyInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K27ac/earlyInc_earlyDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_earlyDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_earlyInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K27ac/earlyInc_lateDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_lateDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_earlyInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K27ac/earlyInc_dec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_dec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_earlyInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K27ac/earlyInc_none -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_noChange_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_lateInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K27ac/lateInc_allDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_allDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_lateInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K27ac/lateInc_earlyDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_earlyDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_lateInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K27ac/lateInc_lateDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_lateDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_lateInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K27ac/lateInc_dec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_dec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_lateInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K27ac/lateInc_none -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K27ac/H3K27ac_noChange_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_dec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/HDAC2/dec_allInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_allInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_dec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/HDAC2/dec_earlyInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_earlyInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_dec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/HDAC2/dec_lateInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_lateInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_dec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/HDAC2/dec_inc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_inc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_dec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/HDAC2/dec_none -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_noChange_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_earlyDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/HDAC2/earlyDec_allInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_allInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_earlyDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/HDAC2/earlyDec_earlyInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_earlyInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_earlyDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/HDAC2/earlyDec_lateInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_lateInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_earlyDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/HDAC2/earlyDec_inc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_inc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_earlyDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/HDAC2/earlyDec_none -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_noChange_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_lateDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/HDAC2/lateDec_allInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_allInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_lateDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/HDAC2/lateDec_earlyInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_earlyInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_lateDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/HDAC2/lateDec_lateInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_lateInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_lateDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/HDAC2/lateDec_inc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_inc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_lateDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/HDAC2/lateDec_none -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_noChange_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_inc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/HDAC2/inc_allDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_allDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_inc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/HDAC2/inc_earlyDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_earlyDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_inc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/HDAC2/inc_lateDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_lateDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_inc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/HDAC2/inc_dec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_dec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_inc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/HDAC2/inc_none -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_noChange_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_earlyInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/HDAC2/earlyInc_allDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_allDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_earlyInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/HDAC2/earlyInc_earlyDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_earlyDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_earlyInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/HDAC2/earlyInc_lateDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_lateDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_earlyInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/HDAC2/earlyInc_dec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_dec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_earlyInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/HDAC2/earlyInc_none -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_noChange_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_lateInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/HDAC2/lateInc_allDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_allDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_lateInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/HDAC2/lateInc_earlyDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_earlyDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_lateInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/HDAC2/lateInc_lateDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_lateDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_lateInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/HDAC2/lateInc_dec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_dec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_lateInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/HDAC2/lateInc_none -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/HDAC2/HDAC2_noChange_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_dec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me3/dec_allInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_allInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_dec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me3/dec_earlyInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_earlyInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_dec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me3/dec_lateInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_lateInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_dec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me3/dec_inc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_inc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_dec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me3/dec_none -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_noChange_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_earlyDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me3/earlyDec_allInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_allInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_earlyDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me3/earlyDec_earlyInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_earlyInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_earlyDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me3/earlyDec_lateInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_lateInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_earlyDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me3/earlyDec_inc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_inc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_earlyDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me3/earlyDec_none -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_noChange_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_lateDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me3/lateDec_allInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_allInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_lateDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me3/lateDec_earlyInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_earlyInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_lateDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me3/lateDec_lateInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_lateInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_lateDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me3/lateDec_inc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_inc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_lateDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me3/lateDec_none -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_noChange_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_inc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me3/inc_allDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_allDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_inc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me3/inc_earlyDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_earlyDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_inc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me3/inc_lateDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_lateDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_inc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me3/inc_dec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_dec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_inc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me3/inc_none -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_noChange_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_earlyInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me3/earlyInc_allDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_allDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_earlyInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me3/earlyInc_earlyDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_earlyDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_earlyInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me3/earlyInc_lateDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_lateDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_earlyInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me3/earlyInc_dec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_dec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_earlyInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me3/earlyInc_none -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_noChange_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_lateInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me3/lateInc_allDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_allDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_lateInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me3/lateInc_earlyDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_earlyDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_lateInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me3/lateInc_lateDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_lateDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_lateInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me3/lateInc_dec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_dec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_lateInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me3/lateInc_none -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me3/H3K4me3_noChange_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_dec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me1/dec_allInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_allInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_dec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me1/dec_earlyInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_earlyInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_dec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me1/dec_lateInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_lateInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_dec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me1/dec_inc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_inc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_dec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me1/dec_none -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_noChange_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_earlyDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me1/earlyDec_allInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_allInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_earlyDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me1/earlyDec_earlyInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_earlyInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_earlyDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me1/earlyDec_lateInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_lateInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_earlyDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me1/earlyDec_inc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_inc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_earlyDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me1/earlyDec_none -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_noChange_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_lateDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me1/lateDec_allInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_allInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_lateDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me1/lateDec_earlyInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_earlyInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_lateDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me1/lateDec_lateInc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_lateInc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_lateDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me1/lateDec_inc -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_inc_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_lateDec_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me1/lateDec_none -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_noChange_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_inc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me1/inc_allDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_allDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_inc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me1/inc_earlyDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_earlyDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_inc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me1/inc_lateDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_lateDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_inc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me1/inc_dec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_dec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_inc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me1/inc_none -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_noChange_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_earlyInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me1/earlyInc_allDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_allDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_earlyInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me1/earlyInc_earlyDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_earlyDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_earlyInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me1/earlyInc_lateDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_lateDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_earlyInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me1/earlyInc_dec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_dec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_earlyInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me1/earlyInc_none -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_noChange_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_lateInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me1/lateInc_allDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_allDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_lateInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me1/lateInc_earlyDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_earlyDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_lateInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me1/lateInc_lateDec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_lateDec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_lateInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me1/lateInc_dec -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_dec_blacklisted.bed  -preparsedDir ~/temp -preparse

./qrun findMotifsGenome.pl /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_lateInc_blacklisted.bed mm9 /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/results/UpdADMouse/mouse/H3K4me1/lateInc_none -size given -bg /srv/gsfs0/projects/kundaje/users/summerStudents/2014/pgreddy/data/UpdADMouse/mouse/H3K4me1/H3K4me1_noChange_blacklisted.bed  -preparsedDir ~/temp -preparse
